SELECT
	   [Bulan Id]
      ,[Bulan]
      ,[CustomerID]
      ,[Kota Id]
      ,[Kota]
      ,[Tanggal Jual]
      ,[Status Id]
      ,[Status]
      ,[Nama Customer]
      ,[Brand Id]
      ,[Brand]
      ,[Tahun Kendaraan Id]
      ,[Tahun Kendaraan]
      ,[Tanggal Repossess]
      ,[Tanggal Inventory]
      ,TRY_CONVERT(DECIMAL(18,2), [Sisa Pokok Hutang]) [Sisa Pokok Hutang]
      ,TRY_CONVERT(DECIMAL(18,2), [Harga Jual]) [Harga Jual]
      ,TRY_CONVERT(DECIMAL(18,2), [Kerugian]) [Kerugian]
      ,[Pembeli]
      ,[Kategori Id]
      ,[Kategori]
      ,[Channel]
      ,[Grade]
      ,[Produk Id]
      ,[Produk]
FROM [Excel_Import].[dbo].[inventory selling]

SELECT
	   [Bulan Id]
      ,[Bulan]
      ,[CustomerID]
      ,[Kota Id]
      ,[Kota]
      ,[Kategori Id]
      ,[Kategori]
      ,[Produk Id]
      ,[Produk]
      ,[Nama Customer]
      ,[Brand Id]
      ,[Brand]
      ,[Tahun Kendaraan Id]
      ,[Tahun Kendaraan]
      ,[Status Id]
      ,[Status]
      ,TRY_CONVERT(DECIMAL(18,2), [Sisa Pokok Hutang]) [Sisa Pokok Hutang]
      ,[Tanggal Repossess]
      ,[Tanggal Inventory]
FROM [Excel_Import].[dbo].[inventory target]


